---
abstract: 'Pegex Parser for 02packages.txt'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pegex-CPAN-Packages
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  Pegex: '0.43'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/pegex-cpan-packages-pm/issues
  homepage: https://github.com/ingydotnet/pegex-cpan-packages-pm
  repository: https://github.com/ingydotnet/pegex-cpan-packages-pm.git
version: '0.04'
